services:
  vkrserver:
    image: ${DOCKER_REGISTRY-}vkrserver
    container_name: vkrserver
    build:
      context: .
      dockerfile: VKRServer/Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ~/.aspnet/https:/https:ro

  vkrdatabase:
    image: postgres:latest
    container_name: vkrdatabase
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vkrdatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: